### ISSUE TITLE
[Contact Request] Multiplayer functions

### ISSUE THREAD

**Issue by dsk80004** [yancharkin/SpelunkyClassicHD#10]
I'm working on adding multiplayer to the current version, I've already added a ton of bug fixes which were implemented in modern Spelunky. If any of the active members/contributors could contact me on Discord at Red#9475 I would like to discuss some updates and bug fixes I've made.

**Comment by dsk80004** [comment]
https://i.gyazo.com/c185f2d3ad7b5cd5fd93be5e54a289d8.mp4

**Comment by yancharkin** [comment]
I'm not using Discord. Why not discuss it here?

**Comment by dsk80004** [comment]
My time spent on Github is erratic at best, although I could post my updates.
Anyways I'm currently working on adding a ton of the bug fixes which were implemented into Spelunky SD by YellowAfterLife, things as small as better jumping collisions, and bones breaking when you whip them, up to the more important changes made in modern Spelunky like the multiplayer functionality, been working on it for about 3 hours a day already have the controls working, and holding items roughly working though with a good number of bugs. I was wondering if there is anything you may be actively working on which might interfere with some of the changes I've made.

Essentially I'm trying to make any changes easy to integrate together into a single fork when it's finished. So If you're working on something or have something planned I would be happy to merge files.

**Comment by yancharkin** [comment]
No, I'm not working on anything and not planning to do so. Actually, until recently, this project was pretty much dead. Only because @nkrapivin  fixed some of the most annoying bugs I decided to invest some time into it. I'm not eager to use the GameMaker engine again. So feel free to implement anything you want. Just make sure new features work and not breaking the game. No need to post updates, writing meaningful git commit messages is enough.

**Comment by dsk80004** [comment]
Alright cool, I'll likely post one large update at a time. Is there
anything you would prefer for me to stay away from?

**Comment by yancharkin** [comment]
> Is there anything you would prefer for me to stay away from?

No, I'm OK with any changes as long as game not broken.

But before you proceed, maybe you should contact @nkrapivin. He mentioned that he was working on his own version of the game based on the original source code (or [SpelunkyCommunityUpdateProject](https://github.com/tyrovc/SpelunkyCommunityUpdateProject)?). That version likely has fewer bugs. But most important that he is a competent GameMaker developer who is working with the engine all the time.

**Comment by dsk80004** [comment]
Sounds great I would imagine he has probably already fixed a lot of the
same issues on his personal version. Does that tag send him a mentioned
notification? Or should I reach out to him myself?

**Comment by yancharkin** [comment]
You should contact him yourself.

**Comment by v9tn** [comment]
@tinkerer-red 
I am interested in this project, were you able to add multiplayer successfully?
Im sorry for asking about this project, which is about 5 years old.
