### ISSUE TITLE
Self-hurting pistols.

### ISSUE THREAD

**Issue by ninjatao** [yancharkin/SpelunkyClassicHD#14]
Hi there, as in 1.1.5, firing pistols while moving or standing at the edge of platform can still hurt player.
Great work btw, I really appreciate your android port on the original game.

**Comment by yancharkin** [comment]
Fixed.
I'm going on a vacation and can't publish new builds now (it takes some time). I'll return in about ten days. If there are any other bugs, report them because the next build likely will be the last I release.

**Comment by yancharkin** [comment]
New builds published.
