### ISSUE TITLE
Un-responsive touch controls

### ISSUE THREAD

**Issue by DBPT210** [yancharkin/SpelunkyClassicHD#17]
Touch controls are very bad in "recent" smartphones. I almost can't play using my Xioami Redmi 6.
I know that this project is not in development anymore, but I think it should still be addressed here.
I'm actually thinking about fixing this myself, but I have no programming experience. Anyway, I will try my best.

**Comment by yancharkin** [comment]
Maybe you should try the [HTML5 version](https://github.com/yancharkin/SpelunkyClassicHDhtml5) first, there is a chance it works better.

I'm not sure it is possible to adjust touch controls sensitivity. But you can try. GM: Studio 1.4 documentation [here](https://docs.yoyogames.com/). Another option is to port the game to GM: Studio 2, maybe it will help, but likely it's not easy.

**Comment by arifhamed** [comment]
I don't think it's exactly unresponsiveness you're meaning of. Currently my android phone (API 30) is over 2:1 ratio, and the actual input areas are slightly closer to the center of the screen than the touch control UI. It makes no sense to me, lest I look at more details of the files first. 

To me, this implies that the the input areas are stretched to fit my screen, but the UI and the game isn't. The latter is good though, just sayin'.

**Comment by yancharkin** [comment]
@arifhamed If that's the case, it should be possible (and relatively easy) to fix it.
At some point, I noticed touch controls not working correctly on some devices and tried to fix that (but I do not test this fix much). It looks like it wasn't good enough. Maybe it even broke something.
You have to modify [this file](https://github.com/yancharkin/SpelunkyClassicHD/blob/master/scripts/enableTouchInput.gml) and/or variables **'global.touchCorrectionH'** and **'global.touchCorrectionV'** (use search to find them). 
First, try to remove them. For example change:
`virtual_key_add(global.touchCorrectionH, global.display_h - (2*vkey_size) - global.touchCorrectionV, vkey_size, vkey_size, global.keyLeftVal);`
to
`virtual_key_add(0, global.display_h - (2*vkey_size), vkey_size, vkey_size, global.keyLeftVal);`
