### ISSUE TITLE
RG351 No Controls

### ISSUE THREAD

**Issue by Rsmith44** [yancharkin/SpelunkyClassicHD#18]
I have an rg351 and download through postmaster. 

When opening the game, start and select open the menu and B goes down (scrolls through options). 

No other buttons function, I therefore can not change the control setup or play the game. 

Thanks

**Comment by yancharkin** [comment]
https://itch.io/t/1025102/android-gamepad-support#post-2108897

**Comment by yancharkin** [comment]
Try HTML5 version, there is a chance that gamepad will work with it.
