### ISSUE TITLE
 Controls touch not working in pc

### ISSUE THREAD

**Issue by Moriand** [yancharkin/SpelunkyClassicHD#2]
hello, in windows 10 does not load the touch mode, can you say how did you do this trick in touch mode?

**Comment by yancharkin** [comment]
As far as I remember replacing

    global.mobileBuild = false;
to

    global.mobileBuild = true;
in [scripts/scrInit.gml](https://github.com/yancharkin/SpelunkyClassicHD/blob/master/scripts/scrInit.gml) should enable on-screen controls.
But I'm not sure touch input supported (by engine) on desktop platforms.

**Comment by yancharkin** [comment]
@Moriand ???

**Comment by yancharkin** [comment]
OK. I took a look at [documentation](http://docs.yoyogames.com/source/dadiospice/002_reference/mouse,%20keyboard%20and%20other%20controls/virtual%20keys/index.html) and now I'm sure touch input not supported on Windows. Closing.

**Comment by yancharkin** [comment]
Touch controls should work in [HTML5 build](https://github.com/yancharkin/SpelunkyClassicHDhtml5).
