### ISSUE TITLE
Jumping Boots not working

### ISSUE THREAD

**Issue by SuperCoolandBadassName** [yancharkin/SpelunkyClassicHD#21]
I know the game is not in development anymore, i just want to report

**Comment by yancharkin** [comment]
Sorry, missed the notification. Jumping boots should work in native desktop builds. I have to

**Comment by yancharkin** [comment]
Sorry, I missed the notification.
Jumping boots should work in native desktop builds. As far as I remember, I made some hacky modifications to Android and HTML5 builds because otherwise, touch controls weren't working correctly.

**Comment by SuperCoolandBadassName** [comment]
Other thing, i played the original version on pc and there is some missing rooms, in mobile you always start a level on the left side of the map, o pc you can start in the middle or the right.Those white squares sometimes swallow the player and crush you in the wall,  and firing a gun while climbing a ladder makes you shoot yourself

**Comment by yancharkin** [comment]
As you already know, I'm not working on this game anymore, so I won't fix these bugs.
In case someone ever resumes development, it's better to report each bug separately.
