### ISSUE TITLE
Add Ukrainian localization

### ISSUE THREAD

**Issue by bakustarver** [yancharkin/SpelunkyClassicHD#22]
I made Ukrainian localization according to the guide

[lang-uk.zip](https://github.com/yancharkin/SpelunkyClassicHD/files/14827746/lang-uk.zip)

![2024-04-01_22-34-45_resized](https://github.com/yancharkin/SpelunkyClassicHD/assets/66978329/ae73e4be-afe6-4065-8a0c-66b3a70cdc95)

![2024-04-01_22-34-55_resized](https://github.com/yancharkin/SpelunkyClassicHD/assets/66978329/a78a2c61-54e0-4cd0-9f2d-56f996a49de2)

![2024-04-01_22-35-46_resized](https://github.com/yancharkin/SpelunkyClassicHD/assets/66978329/ca8f008a-9df6-4778-b3d8-26cc9e4380c1)

**Comment by yancharkin** [comment]
Great! I will add it ASAP.
Дуже дякую!

**Comment by yancharkin** [comment]
Done.
