### ISSUE TITLE
Someone ported Spelunky Classic to GM Studio 2

### ISSUE THREAD

**Issue by bakustarver** [yancharkin/SpelunkyClassicHD#23]
The game starts and works (there are many bugs)
The Ported game is without your modifications

https://github.com/wazawoo/spelunky-classic-mac

**Comment by yancharkin** [comment]
There is at least another one: https://github.com/osum4est/spelunky-switch
It is a fork of my repo, so it has some modifications.
It is likely not too hard to port the game to GMS 2, but I have no time (and not only time) to do it.
