### ISSUE TITLE
Basing on/porintg changes from unofficial Spelunky v1.3?

### ISSUE THREAD

**Issue by singalen** [yancharkin/SpelunkyClassicHD#4]
The unofficial version 1.3 (https://forums.tigsource.com/index.php?topic=28467.0) has (had?) quite a lot of fixes.
Their file downloads are down now, but I believe I found the fork: https://github.com/tyrovc/SpelunkyCommunityUpdateProject, with a confirmation that it's that one: http://mossmouth.com/forums/index.php?topic=1257.90 (see mentions of idyll and TyrOvC)

**Comment by yancharkin** [comment]
I'm not planning to work on this project anymore (have to update the README) and even if it wasn't the case, porting changes from 1.3 just too much works, sorry.

Here some details if you'll decide to do it yourself:
- 1.3 using Game Maker 8 (or even 7?) and my version using Game Maker Studio 1.4
- my version based on this [port](http://tinysubversions.com/2012/07/spelunky-html5/), that has a number of serious issues
- it's better (but probably much harder) to port 1.3 to Game Maker Studio 1.4 (or 2 if it's possible) and then incorporate my changes
