### ISSUE TITLE
Linux YYC version does not link to all libraries appropriately

### ISSUE THREAD

**Issue by StopIteration** [yancharkin/SpelunkyClassicHD#9]
The 1.1.4 `spelunky_classic_hd-linux-i386-yyc.zip` release is unable to find `libidn.so.11` and `librtmp.so.0` on my system.  These are included in the lib directory, but the game doesn't link to them.  However, the non-YYC version does correctly link to them.

For players, the workaround is adding the lib directory to LD_LIBRARY_PATH when running the game or using the non-YYC version.

**Comment by yancharkin** [comment]
I'm was aware of this problem, but I wasn't sure what to do about it. Now I have a better idea of what can be done. What distro are you using? Is it 64-bit or 32-bit?

**Comment by yancharkin** [comment]
Actually, on second thoughts, it doesn't matter what distro you are using. I was thinking about creating proper packages (mostly for resolving dependencies easily). But it's not worth the effort and in some cases even impossible, libraries used by the engine are too old and I have to bundle at least some of them anyway (which invalidates benefits of using a package manager).
So I added launch script and repackaged the game archive. Now YYC build should work out of the box. If you can test it and give your feedback, it will be great.

**Comment by StopIteration** [comment]
The launch script works for me.  The script could be slightly improved I think by using `exec` to start the game, i.e. `exec "${DIR}/spelunky.bin"` so that the bash process is replaced.  I'd say this issue is pretty much resolved, but of course it would be better if the binary linked to bundled libraries rather than needing `LD_LIBRARY_PATH` hacks.  It is interesting to me that `ldd` shows that most of the libraries are linked correctly to the bundled ones, it's just those two that are not.  But I don't know anything about gamemaker and not too much about shared libraries either so I have no clue how to fix that, but I want to believe there's a way to get YYC to link those libraries correctly.

**Comment by yancharkin** [comment]
Good idea with using exec, I did it.
Regarding hacks, I have to use them anyway. Binaries produced by Gamemaker use system libraries, and there is no way to change that (at least no way that worth the effort). To make it possible to bundle libraries (I have to do it for various reasons), I have to either use LD_LIBRARY_PATH or set RUNPATH using patchelf. Setting RUNPATH works fine for the non-YYC build, but for YYC build, it doesn't work. I have an idea why, but, again, fixing it not worth the effort  (even if I'm not wrong). I'm OK with using the launch script. 
Also on Linux, it's more practical to use this version (unless you want to run the game on the really old computer): https://github.com/yancharkin/SpelunkyClassicHDhtml5/releases
